services:
  main:
    restart: always
    build:
      context: .
    container_name: algora
    ports:
      - "5000:5000"
    environment:
      - PORT=:5000
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true
