// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Algorithm struct {
	ID          int32
	TextID      string
	Name        string
	Type        int16
	Position    int16
	Explanation string
	HasCode     bool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type AlgorithmCode struct {
	ID          int32
	AlgorithmID int32
	Language    string
	Code        string
}

type User struct {
	ID           uuid.UUID
	Email        string
	Username     string
	Role         string
	PasswordHash []byte
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
