// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Algorithm struct {
	ID          int32
	TextID      string
	Name        string
	Type        string
	Explanation string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type AlgorithmCodeFile struct {
	ID          int32
	AlgorithmID sql.NullInt64
	Filename    sql.NullString
	Language    sql.NullString
}

type User struct {
	ID           uuid.UUID
	Email        string
	Username     string
	Role         string
	PasswordHash []byte
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
